version: "3.3"

services:
  jaegertracing:
    image: jaegertracing/all-in-one:1.41.0
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      # - "5775:5775/udp" # Agent - deprecated; only used by very old Jaeger clients
      # - "6831:6831/udp" # Agent - Thrift protocol used by most current Jaeger clients
      # - "6832:6832/udp" # Agent - protocol for Node.js Jaeger client
      # - "5778:5778"     # Agent - serve configs, sampling strategies
      - "16686:16686"   # Web UI
      - "14268:14268"   # Collector - HTTP can accept spans directly from clients in jaeger.thrift format over binary thrift protocol
      # - "14250:14250"   # Collector - used by jaeger-agent to send spans in model.proto format
      # - "4317:4317"     # Collector - OTLP gRPC
      - "4318:4318"     # Collector - OTLP HTTP